### ISSUE TITLE
Marking a record as ^:no-doc still shows the constructor functions (->Foo and map->Foo)

### ISSUE THREAD

**Issue by hlship** [weavejester/codox#92]
It seems to me that if you are hiding the existence of the record, your should hide the constructors as well.  Make sense?

Observed in 0.8.12.

**Comment by weavejester** [comment]
What if someone wants the record to be undocumented, but the `->Foo` and `map->Foo` functions to be documented? How would you support that if setting `:no-doc` on the record automatically sets it on the constructors?

**Comment by hlship** [comment]
Yep, it's tricky ... I suppose you could use vary-meta on the ->Foo and
map->Foo functions?

On Fri, May 15, 2015 at 12:18 PM, James Reeves <notifications@github.com>
wrote:

> What if someone wants the record to be undocumented, but the ->Foo and
> map->Foo functions to be documented? How would you support that if
> setting :no-doc on the record automatically sets it on the constructors?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/weavejester/codox/issues/92#issuecomment-102498222>.
>



-- 
Howard M. Lewis Ship

Creator of Apache Tapestry

The source for Tapestry training, mentoring and support. Contact me to
learn how I can get you up and productive in Tapestry fast!

(971) 678-5210
http://howardlewisship.com
@hlship

**Comment by weavejester** [comment]
The `->Foo` and `map->Foo` wouldn't have any `:no-doc` metadata on them, so we'd need another metadata key to override metadata held on the record.

What I might do is add support to ignore vars matching a certain pattern, then add a default pattern of `#"^(map)?->\p{Upper}"`, since most of the time people don't want to see the constructors in their docs.
